CREATE OR REPLACE WAREHOUSE COMPUTE_WAREHOUSE
WITH 
WAREHOUSE_SIZE=XSMALL
MAX_CLUSTER_COUNT=1
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = FALSE
COMMENT = 'This is our second WAREHOUSE';
USE DATABASE snowflake_sample_data;
grant imported privileges on database snowflake_sample_data to public;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
DROP WAREHOUSE COMPUTE_WAREHOUSE;
